# Generated by Django 5.2.6 on 2025-09-11 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categoria',
                'db_table': 'Category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=50, unique=True, verbose_name='Moeda')),
                ('country', models.CharField(max_length=3, unique=True, verbose_name='País')),
                ('symbol', models.CharField(max_length=3, unique=True, verbose_name='Símbolo')),
            ],
            options={
                'verbose_name_plural': 'Moeda',
                'db_table': 'coin',
                'ordering': ['coin'],
            },
        ),
        migrations.CreateModel(
            name='ModelTypeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='Tipo da Conta')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Tipo de conta',
                'db_table': 'tipo_conta',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='ModelAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('operation', models.CharField(choices=[('ativos', 'Ativos'), ('despesas', 'Despesas'), ('receitas', 'Receitas'), ('passivos', 'Passivos')], max_length=50, verbose_name='Operação')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins_account', to='registers.modelcoin', verbose_name='Moeda')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.modeltypeaccount', verbose_name='Tipo de Conta')),
            ],
            options={
                'verbose_name_plural': 'Contas',
                'db_table': 'contas',
                'ordering': ['operation'],
            },
        ),
    ]
