# Generated by Django 5.2.6 on 2025-09-11 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nome')),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('invoice', models.DateField(verbose_name='Data da Fatura')),
                ('note', models.IntegerField(verbose_name='Numero da Nota')),
                ('accont_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='registers.modelaccount', verbose_name='Conta destino')),
                ('accont_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='registers.modelaccount', verbose_name='Conta origem')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='registers.modelcategory', verbose_name='Categoria')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='registers.modelcoin', verbose_name='Moeda')),
            ],
        ),
        migrations.CreateModel(
            name='ModelImagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='note/', verbose_name='Imagnes')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app.modeloperations', verbose_name='Operação')),
            ],
            options={
                'verbose_name_plural': 'Imagens',
                'db_table': 'imagens',
            },
        ),
    ]
